events {}

http {
  server {
    listen 80;

    location / {
      root /usr/share/nginx/html;
      index index.html;
    }

    location /api {      
      proxy_pass http://test-k8sapi-service:3000;
    }
  }
}
