apiVersion: v1
kind: Service
metadata:
  name: test-k8sapi-service
spec:
  type: NodePort
  selector:
    app: test-k8sapi
  ports:
    - port: 3000            # Port other services use to reach this
      targetPort: 3000      # Port the container listens on
      nodePort: 30081
