apiVersion: v1
kind: Service
metadata:
  name: backend-service          # ⭐ CHANGE NAME
spec:
  type: NodePort
  selector:
    app: backend                 # ⭐ MUST MATCH deployment label
  ports:
    - port: 3000                 # service port
      targetPort: 3000           # container port
      nodePort: 30008            # ⭐ CHANGE ANY 30000–32767
