apiVersion: v1
kind: Service
metadata:
  name: test-k8sfrontend-service
spec:
  type: NodePort
  selector:
    app: test-k8sfrontend           # Must exactly match deployment label
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
