apiVersion: v1
kind: Service
metadata:
  name: frontend-service          # ⭐ CHANGE
spec:
  type: NodePort
  selector:
    app: frontend                 # ⭐ MUST MATCH LABEL
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007             # ⭐ CHANGE 5 digit port
