apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    nginx.ingress.kubernetes.io/rewrite-target: /$2     # kept for compatibility

spec:
  ingressClassName: traefik              # k3s uses Traefik — NOT nginx

  rules:
    - http:
        paths:
          
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend       # Must match backend-service.yaml
                port:
                  number: 3000
         
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service      # Must match frontend-service.yaml
                port:
                  number: 80