apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service          # ⭐ CHANGE NAME
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Values.backend.name }}                 # ⭐ MUST MATCH deployment label
  ports:
    - port: {{ .Values.backend.service.port }}                 # service port
      targetPort: {{ .Values.backend.containerPort }}           # container port
      nodePort: {{ .Values.backend.service.nodePort }}            # ⭐ CHANGE ANY 30000–32767
