apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen {{ .Values.frontend.containerPort | default 80 }};
        
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }

        location /api {
          proxy_pass http://{{ .Release.Name }}-backend-service{{ if .Values.backend.service.port }}:{{ .Values.backend.service.port }}{{ else }}:3000{{ end }};
        }
      }
    }
